[workspace]
members = [
    "apk",
    "appbundle",
    "appimage",
    "dmg",
    "mvn",
    "msix",
    "pri",
    "xbuild",
    "xcommon",
]
default-members = ["xbuild"]
exclude = ["examples"]

[patch.crates-io]
aws-smithy-xml = { path = "../smithy-rs/rust-runtime/aws-smithy-xml" }
