[workspace]
members = [
    "apk",
    "appbundle",
    "appimage",
    "mvn",
    "msix",
    "pri",
    "xbuild",
    "xcommon",
]
default-members = ["xbuild"]
exclude = ["examples"]

[patch.crates-io]
apple-codesign = { git = "https://github.com/indygreg/apple-platform-rs", branch = "main" }
