[workspace]
members = [
    "apk",
    "appbundle",
    "appimage",
    "mvn",
    "msix",
    "pri",
    "xbuild",
    "xcommon",
]
default-members = ["xbuild"]
exclude = ["examples"]

[workspace.dependencies]
rasn = "0.17.3"
rasn-cms = "0.17.3"
rasn-pkix = "0.17.3"
