[workspace]
members = [
    "apk",
    "appbundle",
    "appimage",
    "examples/flutter",
    #"examples/rust",
    "maven",
    "msix",
    "xcli",
    "xcommon",
]
default-members = ["xcli"]
exclude = ["examples/raqote-winit"]
