[package]
name = "pri"
version = "0.2.0"
edition = "2021"
description = "Library for creating and parsing pri files."
repository = "https://github.com/rust-mobile/xbuild"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = { workspace = true }
byteorder = { workspace = true }
