[package]
name = "appbundle"
version = "0.2.0"
edition = "2021"
description = "Library for creating and signing appbundles."
repository = "https://github.com/cloudpeers/x"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0.53"
#apple-codesign = "0.13.0"
apple-codesign = { git = "https://github.com/dvc94ch/pyoxidizer", branch = "fix-zips" }
icns = "0.3.1"
log = "0.4.16"
pkcs8 = "0.8.0"
plist = "1.3.1"
rasn = "0.5.0"
rasn-cms = "0.5.0"
serde = { version = "1.0.136", features = ["derive"] }
#x509-certificate = "0.12.0"
x509-certificate = { git = "https://github.com/dvc94ch/pyoxidizer", branch = "fix-zips" }
xcommon = { version = "0.2.0", path = "../xcommon" }
