[package]
name = "msix"
version = "0.2.0"
edition = "2021"
description = "Library for creating and signing msix packages."
repository = "https://github.com/cloudpeers/x"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0.53"
base64 = "0.13.0"
byteorder = "1.4.3"
mime_guess = "2.0.3"
quick-xml = { version = "0.23.0-alpha2", features = ["serialize"] }
rasn = "0.5.0"
rasn-cms = "0.5.0"
rasn-pkix = "0.5.0"
serde = { version = "1.0.136", features = ["derive"] }
sha2 = "0.10.1"
xcommon = { version = "0.1.0", path = "../xcommon" }
zip = { version = "0.6.0", default-features = false }

[dev-dependencies]
der-parser = "7.0.0"
rsa = "0.6.0"
