on:
  push:
    branches:
    - master
  pull_request:

name: x

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        components: clippy, rustfmt
    - run: cargo fmt --all -- --check
    #- run: cargo clippy --workspace --examples --tests --all-features -- -D warnings

  build:
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest]
    runs-on: ${{ matrix.host }}
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
    - run: cargo install --path xcli --root .
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.host }}-x
        path: bin/x
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.host }}-xrun
        path: bin/xrun

  build-linux-x64-debug:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest]
        artifact: [helloworld]
    runs-on: ${{ matrix.host }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.host }}-x
    - run: sudo apt-get update && sudo apt-get install libgtk-3-dev
    - uses: hecrj/setup-rust-action@v1
      with:
        targets: x86_64-unknown-linux-gnu
    - uses: subosito/flutter-action@v1
    - run: chmod +x ./x
    - run: ./x build -p ${{ matrix.artifact }} --platform linux --arch x64
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.host }}-linux-x64-debug-${{ matrix.artifact }}
        path: target/x/debug/linux/x64/${{ matrix.artifact }}.AppDir

  run-linux-x64-debug:
    needs: build-linux-x64-debug
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest]
        artifact: [helloworld]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.host }}-linux-x64-debug-${{ matrix.artifact }}
    - uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.host }}-xrun
    - run: chmod +x ./xrun
    - run: ./xrun --path ${{ matrix.artifact }}.AppDir/AppRun

  build-linux-x64-release:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest]
        artifacts: [helloworld]
    runs-on: ${{ matrix.host }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.host }}-x
    - run: sudo apt-get update && sudo apt-get install libgtk-3-dev squashfs-tools
    - uses: hecrj/setup-rust-action@v1
      with:
        targets: x86_64-unknown-linux-gnu
    - uses: subosito/flutter-action@v1
    - run: chmod +x ./x
    - run: ./x build -p ${{ matrix.artifact }} --platform linux --arch x64 --release
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.host }}-linux-x64-release-${{ matrix.artifact }}
        path: target/x/release/linux/x64/${{ matrix.artifact }}.AppImage

  run-linux-x64-release:
    needs: build-linux-x64-release
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest]
        artifact: [helloworld]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.host }}-linux-x64-release-${{ matrix.artifact }}
    - uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.host }}-xrun
    - run: chmod +x ./xrun
    - run: ./xrun --path ${{ matrix.artifact }}.AppImage
